name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build core package
        run: |
          cd packages/core
          npm ci
          npm run build:prod

      - name: Build react package
        run: |
          cd packages/react
          npm ci
          npm run build:prod

      - name: Build plugins package
        run: |
          cd packages/plugins
          npm ci
          npm run build:prod

      - name: Build testing package
        run: |
          cd packages/testing
          npm ci
          npm run build:prod

      - name: Build website
        run: |
          cd website
          npm ci
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './website/build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 