name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to publish (e.g., v0.0.3)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify tag exists
        run: |
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "Error: Tag '${{ github.event.inputs.tag }}' does not exist"
            echo "Available tags:"
            git tag
            exit 1
          fi
          echo "Tag '${{ github.event.inputs.tag }}' found"

      - name: Checkout specific tag
        run: |
          git fetch origin tag ${{ github.event.inputs.tag }}
          git checkout ${{ github.event.inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build packages
        run: npx turbo run build:prod

      - name: Publish packages
        run: npm run publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 